In [105]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [106]:
import pandas as pd

### html file  :

https://www.teoalida.com/cardatabase/samples/Car-Models-List-by-Teoalida-SAMPLE.csv
https://www.teoalida.com/cardatabase/
https://datahub.io/machine-learning/autos

In [107]:
pd.read_csv("addresses.csv")

id  location_id                   address_1  address_2  \
0    1            1       2600 Middlefield Road        NaN   
1    2            2            24 Second Avenue        NaN   
2    3            3            24 Second Avenue        NaN   
3    4            4            24 Second Avenue        NaN   
4    5            5            24 Second Avenue        NaN   
5    6            6           800 Middle Avenue        NaN   
6    7            7              500 Arbor Road        NaN   
7    8            8           800 Middle Avenue        NaN   
8    9            9       2510 Middlefield Road        NaN   
9   10           10       1044 Middlefield Road        NaN   
10  11           11         2140 Euclid Avenue.        NaN   
11  12           12       1044 Middlefield Road  2nd Floor   
12  13           13         399 Marine Parkway.        NaN   
13  14           14          660 Veterans Blvd.        NaN   
14  15           15        1500 Valencia Street        NaN   
15  16           16         1161 South Bernardo        NaN   
16  17           17     409 South Spruce Avenue        NaN   
17  18           18            114 Fifth Avenue        NaN   
18  19           19         19 West 39th Avenue        NaN   
19  20           21          123 El Camino Real        NaN   
20  21           22  2013 Avenue of the fellows  Suite 100   

                   city state_province postal_code country  
0          Redwood City             CA       94063      US  
1             San Mateo             CA       94401      US  
2             San Mateo             CA       94403      US  
3             San Mateo             CA       94401      US  
4             San Mateo             CA       94401      US  
5            Menlo Park             CA  94025-9881      US  
6            Menlo Park             CA       94025      US  
7            Menlo Park             CA  94025-9881      US  
8          Redwood City             CA       94063      US  
9          Redwood City             CA       94063      US  
10         Redwood City             CA       94061      US  
11         Redwood City             CA       94063      US  
12         Redwood City             CA       94065      US  
13         Redwood City             CA       94063      US  
14        San Francisco             CA       94110      US  
15            Sunnyvale             CA       94087      US  
16  South San Francisco             CA       94080      US  
17         Redwood City             CA       94063      US  
18            San Mateo             CA       94403      US  
19              Belmont             CA       94002      US  
20        San Francisco             CA       94103      US

In [108]:
pd.read_csv("Vehicle Specifications.csv")

normalized-losses         make fuel-type aspiration num-of-doors  \
0                  NaN  alfa-romero       gas        std          two   
1                  NaN  alfa-romero       gas        std          two   
2                  NaN  alfa-romero       gas        std          two   
3                164.0         audi       gas        std         four   
4                164.0         audi       gas        std         four   
..                 ...          ...       ...        ...          ...   
200               95.0        volvo       gas        std         four   
201               95.0        volvo       gas      turbo         four   
202               95.0        volvo       gas        std         four   
203               95.0        volvo    diesel      turbo         four   
204               95.0        volvo       gas      turbo         four   

      body-style drive-wheels engine-location  wheel-base  length  ...  \
0    convertible          rwd           front        88.6   168.8  ...   
1    convertible          rwd           front        88.6   168.8  ...   
2      hatchback          rwd           front        94.5   171.2  ...   
3          sedan          fwd           front        99.8   176.6  ...   
4          sedan          4wd           front        99.4   176.6  ...   
..           ...          ...             ...         ...     ...  ...   
200        sedan          rwd           front       109.1   188.8  ...   
201        sedan          rwd           front       109.1   188.8  ...   
202        sedan          rwd           front       109.1   188.8  ...   
203        sedan          rwd           front       109.1   188.8  ...   
204        sedan          rwd           front       109.1   188.8  ...   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
0           mpfi  3.47    2.68               9.0      111.0    5000.0   
1           mpfi  3.47    2.68               9.0      111.0    5000.0   
2           mpfi  2.68    3.47               9.0      154.0    5000.0   
3           mpfi  3.19    3.40              10.0      102.0    5500.0   
4           mpfi  3.19    3.40               8.0      115.0    5500.0   
..           ...   ...     ...               ...        ...       ...   
200         mpfi  3.78    3.15               9.5      114.0    5400.0   
201         mpfi  3.78    3.15               8.7      160.0    5300.0   
202         mpfi  3.58    2.87               8.8      134.0    5500.0   
203          idi  3.01    3.40              23.0      106.0    4800.0   
204         mpfi  3.78    3.15               9.5      114.0    5400.0   

    city-mpg  highway-mpg    price  symboling  
0         21           27  13495.0          3  
1         21           27  16500.0          3  
2         19           26  16500.0          1  
3         24           30  13950.0          2  
4         18           22  17450.0          2  
..       ...          ...      ...        ...  
200       23           28  16845.0         -1  
201       19           25  19045.0         -1  
202       18           23  21485.0         -1  
203       26           27  22470.0         -1  
204       19           25  22625.0         -1  

[205 rows x 26 columns]

In [109]:

import pandas as pd

!pip install lxml

In [110]:
data = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [111]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [112]:
### pandas.DataFrame.dtypes( https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html)
### https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes

data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [113]:
### pandas.DataFrame.describe 
### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
### The mean, standard deviation, min and max values
### 
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [114]:
### pandas.DataFrame.info 
### (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [115]:
### https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html
### The number of unique values
### The top (most frequent) value
### The frequency of your top value

data[["Name" , "Sex" , "Ticket"]].describe()

Name   Sex  Ticket
count                       891   891     891
unique                      891     2     681
top     Braund, Mr. Owen Harris  male  347082
freq                          1   577       7

### Pandas Series is :

- A one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.). 
- The axis labels are collectively called index. Pandas Series is nothing but a column in an excel sheet.
- Labels need not be unique but must be a hashable type. 
- The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.

https://www.geeksforgeeks.org/python-pandas-series/

In [116]:
### 
type(data.dtypes)

pandas.core.series.Series

### Pandas dtype mapping :
https://pbpython.com/pandas_dtypes.html

In [117]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [118]:
### Find object(True) 

data.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [119]:
### ### Find object(True) and fillter object 

data.dtypes[data.dtypes == "object" ] 

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [120]:
### Show INDEX :

data.dtypes[data.dtypes == "object" ].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [121]:
### Show data in chart :

data[data.dtypes[data.dtypes == "object" ].index]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [122]:
data[data.dtypes[data.dtypes == "object" ].index].describe() 

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [123]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Question : Try to filter out only a DATASET where " Survived" equals to zero ?????

In [124]:
data["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [125]:
data["Survived"] == 0

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

### Question : Try to filter out only a DATASET where " Survived" equals to zero and  "Male" ?????

In [126]:
data[(data["Survived"] == 0) & (data["Sex"] == "male") ]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
881          882         0       3              Markun, Mr. Johann  male   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
881  33.0      0      0            349257   7.8958   NaN        S  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
890  32.0      0      0            370376   7.7500   NaN        Q  

[468 rows x 12 columns]

In [127]:
### Lets count all data :
data[(data["Survived"] == 0) & (data["Sex"] == "male")].count()

PassengerId    468
Survived       468
Pclass         468
Name           468
Sex            468
Age            360
SibSp          468
Parch          468
Ticket         468
Fare           468
Cabin           62
Embarked       468
dtype: int64

In [128]:
### male :

len(data[(data["Survived"] == 0) & (data["Sex"] == "male")])

468

In [129]:
### female :

len(data[(data["Survived"] == 0) & (data["Sex"] == "female")])

81

In [130]:
### Question about number of female and male :

data["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [131]:
data["Sex"] == "male"

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [132]:
## Filttering "male" data :

data[data["Sex"] == "male"]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [133]:
len(data[data["Sex"] == "male"])

577

In [134]:
## Filttering "female" data :

data["Sex"] == "female"

0      False
1       True
2       True
3       True
4      False
       ...  
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [135]:
data[data["Sex"] == "female"]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [136]:
len(data["Sex"] == "female")

891

### question: How many male and felale survived ?

- change-----> "Survived" == 0      to "Survived" == 1

In [137]:
len(data[(data["Survived"] == 1) & (data["Sex"] == "male")])

109

In [138]:
len(data[(data["Survived"] == 1) & (data["Sex"] == "female")])

233

In [139]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### question: can you please give me a name of person who has a highest fare ?

In [140]:
max(data["Fare"])

512.3292

In [141]:
data["Fare"] == max(data["Fare"])

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [142]:
### Max Fare is : 512.3292 3 Persons 1 person is Survived .

data[data["Fare"] == max(data["Fare"])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [143]:
### Number of persons :

len(data[data["Fare"] == max(data["Fare"])])

3

In [144]:
### Find a name of person :

data[data["Fare"] == max(data["Fare"])]["Name"]

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [145]:
data[data["Fare"] == max(data["Fare"])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [146]:
##Person Fare 0 and survived

data[data["Fare"] == min(data["Fare"])]

PassengerId  Survived  Pclass                              Name   Sex  \
179          180         0       3               Leonard, Mr. Lionel  male   
263          264         0       1             Harrison, Mr. William  male   
271          272         1       3      Tornquist, Mr. William Henry  male   
277          278         0       2       Parkes, Mr. Francis "Frank"  male   
302          303         0       3   Johnson, Mr. William Cahoone Jr  male   
413          414         0       2    Cunningham, Mr. Alfred Fleming  male   
466          467         0       2             Campbell, Mr. William  male   
481          482         0       2  Frost, Mr. Anthony Wood "Archie"  male   
597          598         0       3               Johnson, Mr. Alfred  male   
633          634         0       1     Parr, Mr. William Henry Marsh  male   
674          675         0       2        Watson, Mr. Ennis Hastings  male   
732          733         0       2              Knight, Mr. Robert J  male   
806          807         0       1            Andrews, Mr. Thomas Jr  male   
815          816         0       1                  Fry, Mr. Richard  male   
822          823         0       1   Reuchlin, Jonkheer. John George  male   

      Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
179  36.0      0      0    LINE   0.0   NaN        S  
263  40.0      0      0  112059   0.0   B94        S  
271  25.0      0      0    LINE   0.0   NaN        S  
277   NaN      0      0  239853   0.0   NaN        S  
302  19.0      0      0    LINE   0.0   NaN        S  
413   NaN      0      0  239853   0.0   NaN        S  
466   NaN      0      0  239853   0.0   NaN        S  
481   NaN      0      0  239854   0.0   NaN        S  
597  49.0      0      0    LINE   0.0   NaN        S  
633   NaN      0      0  112052   0.0   NaN        S  
674   NaN      0      0  239856   0.0   NaN        S  
732   NaN      0      0  239855   0.0   NaN        S  
806  39.0      0      0  112050   0.0   A36        S  
815   NaN      0      0  112058   0.0  B102        S  
822  38.0      0      0   19972   0.0   NaN        S

In [147]:
data[data["Fare"] == max(data["Fare"])]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [148]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Question :Find person who have receved a Cabin?

In [149]:
data["Cabin"] != "NaN"

0      True
1      True
2      True
3      True
4      True
       ... 
886    True
887    True
888    True
889    True
890    True
Name: Cabin, Length: 891, dtype: bool

### Check for NaN Value in Pandas DataFrame :
- NaN, which stands for not-a-number, is a numeric type. This means that NaN can appear in columns of type "int" and "float".

- The ways to check for NaN in Pandas DataFrame are as follows: 

    - Check for NaN with isnull().values.any() method
    - Count the NaN Using isnull().sum() Method
    - Check for NaN Using isnull().sum().any() Method
    - Count the NaN Using isnull().sum().sum() Method

In [150]:
data[data["Cabin"] != "NaN"]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Pandas DataFrame isnull() Method

- The isnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, 
- and otherwise False.
- Pandas isnull() and notnull() methods are used to check and manage NULL values in a data frame.

- NaN value is one of the major problems in Data Analysis. It is very essential to deal with NaN in order to get the desired results.

In [151]:
data["Cabin"].isnull()

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [152]:
### Change to "False" and there is no "NaN" in chart :

data[data["Cabin"].isnull() == False]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[204 rows x 12 columns]

In [153]:
### 204 person who have recived cabin.

len(data[data["Cabin"].isnull() == False])

204

In [154]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### Adding new column to existing DataFrame in Pandas

In [155]:
data["New_col"] = "Farshid"

In [156]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  New_col  
0        0         A/5 21171   7.2500   NaN        S  Farshid  
1        0          PC 17599  71.2833   C85        C  Farshid  
2        0  STON/O2. 3101282   7.9250   NaN        S  Farshid  
3        0            113803  53.1000  C123        S  Farshid  
4        0            373450   8.0500   NaN        S  Farshid  
..     ...               ...      ...   ...      ...      ...  
886      0            211536  13.0000   NaN        S  Farshid  
887      0            112053  30.0000   B42        S  Farshid  
888      2        W./C. 6607  23.4500   NaN        S  Farshid  
889      0            111369  30.0000  C148        C  Farshid  
890      0            370376   7.7500   NaN        Q  Farshid  

[891 rows x 13 columns]

In [157]:
### Add new_Text

data["New_text"] = data["Name"]

In [158]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  New_col  \
0        0         A/5 21171   7.2500   NaN        S  Farshid   
1        0          PC 17599  71.2833   C85        C  Farshid   
2        0  STON/O2. 3101282   7.9250   NaN        S  Farshid   
3        0            113803  53.1000  C123        S  Farshid   
4        0            373450   8.0500   NaN        S  Farshid   
..     ...               ...      ...   ...      ...      ...   
886      0            211536  13.0000   NaN        S  Farshid   
887      0            112053  30.0000   B42        S  Farshid   
888      2        W./C. 6607  23.4500   NaN        S  Farshid   
889      0            111369  30.0000  C148        C  Farshid   
890      0            370376   7.7500   NaN        Q  Farshid   

                                              New_text  
0                              Braund, Mr. Owen Harris  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                               Heikkinen, Miss. Laina  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                             Allen, Mr. William Henry  
..                                                 ...  
886                              Montvila, Rev. Juozas  
887                       Graham, Miss. Margaret Edith  
888           Johnston, Miss. Catherine Helen "Carrie"  
889                              Behr, Mr. Karl Howell  
890                                Dooley, Mr. Patrick  

[891 rows x 14 columns]

### Adding new DataFrame to Sumation "Age" and "Pclass" :

In [159]:
data["Age_Pclass"] = data["Age"]  +  data["Pclass"]

In [160]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  New_col  \
0        0         A/5 21171   7.2500   NaN        S  Farshid   
1        0          PC 17599  71.2833   C85        C  Farshid   
2        0  STON/O2. 3101282   7.9250   NaN        S  Farshid   
3        0            113803  53.1000  C123        S  Farshid   
4        0            373450   8.0500   NaN        S  Farshid   
..     ...               ...      ...   ...      ...      ...   
886      0            211536  13.0000   NaN        S  Farshid   
887      0            112053  30.0000   B42        S  Farshid   
888      2        W./C. 6607  23.4500   NaN        S  Farshid   
889      0            111369  30.0000  C148        C  Farshid   
890      0            370376   7.7500   NaN        Q  Farshid   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 15 columns]

In [161]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  New_col  \
0      0         A/5 21171   7.2500   NaN        S  Farshid   
1      0          PC 17599  71.2833   C85        C  Farshid   
2      0  STON/O2. 3101282   7.9250   NaN        S  Farshid   
3      0            113803  53.1000  C123        S  Farshid   
4      0            373450   8.0500   NaN        S  Farshid   

                                            New_text  Age_Pclass  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                             Heikkinen, Miss. Laina        29.0  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                           Allen, Mr. William Henry        38.0

### Delete  new DataFrame with "drop()  :
- axis = 1 -----> Colume
- axis = 0 -----> Rows

In [162]:
data.drop("New_col" , axis=1) 

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

In [163]:
### "New_col" is not delete in original file .

data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  New_col  \
0      0         A/5 21171   7.2500   NaN        S  Farshid   
1      0          PC 17599  71.2833   C85        C  Farshid   
2      0  STON/O2. 3101282   7.9250   NaN        S  Farshid   
3      0            113803  53.1000  C123        S  Farshid   
4      0            373450   8.0500   NaN        S  Farshid   

                                            New_text  Age_Pclass  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                             Heikkinen, Miss. Laina        29.0  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                           Allen, Mr. William Henry        38.0

### Delet rows forever:

### Drop signature :
Signature:
- data.drop(
    - labels: 'IndexLabel' = None,
    *,
    - axis: 'Axis' = 0,
    - index: 'IndexLabel' = None,
    - columns: 'IndexLabel' = None,
    - level: 'Level' = None,
    - inplace: 'bool' = False,------------>delete 
    - errors: 'IgnoreRaise' = 'raise',

In [164]:
data.drop("New_col" , axis=1 , inplace=True) 

In [165]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  \
0      0         A/5 21171   7.2500   NaN        S   
1      0          PC 17599  71.2833   C85        C   
2      0  STON/O2. 3101282   7.9250   NaN        S   
3      0            113803  53.1000  C123        S   
4      0            373450   8.0500   NaN        S   

                                            New_text  Age_Pclass  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                             Heikkinen, Miss. Laina        29.0  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                           Allen, Mr. William Henry        38.0

### Difference between loc() and iloc() in Pandas DataFrame :

- The loc() function is label based data selecting method which means that we have to pass the name of the row or column which we want to select. This method includes the last element of the range passed in it, unlike iloc(). loc() can accept the boolean data unlike iloc(). 

- از اندیس سطر و ستون برای دسترسی

- The iloc() function is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column. This method does not include the last element of the range passed in it unlike loc(). iloc() does not accept the boolean data unlike loc().

- متد از لیبل یا برچسب سطر و ستون برای دسترسی به آن استفاده می‌کند


### Can you Extract Row number 1 :

In [166]:
data.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
New_text       Braund, Mr. Owen Harris
Age_Pclass                        25.0
Name: 0, dtype: object

In [167]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  \
0      0         A/5 21171   7.2500   NaN        S   
1      0          PC 17599  71.2833   C85        C   
2      0  STON/O2. 3101282   7.9250   NaN        S   
3      0            113803  53.1000  C123        S   
4      0            373450   8.0500   NaN        S   

                                            New_text  Age_Pclass  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                             Heikkinen, Miss. Laina        29.0  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                           Allen, Mr. William Henry        38.0

In [168]:
data.loc[20:30]

PassengerId  Survived  Pclass  \
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   
30           31         0       1   

                                                 Name     Sex   Age  SibSp  \
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
29                                Todoroff, Mr. Lalio    male   NaN      0   
30                           Uruchurtu, Don. Manuel E    male  40.0      0   

    Parch    Ticket      Fare        Cabin Embarked  \
20      0    239865   26.0000          NaN        S   
21      0    248698   13.0000          D56        S   
22      0    330923    8.0292          NaN        Q   
23      0    113788   35.5000           A6        S   
24      1    349909   21.0750          NaN        S   
25      5    347077   31.3875          NaN        S   
26      0      2631    7.2250          NaN        C   
27      2     19950  263.0000  C23 C25 C27        S   
28      0    330959    7.8792          NaN        Q   
29      0    349216    7.8958          NaN        S   
30      0  PC 17601   27.7208          NaN        C   

                                             New_text  Age_Pclass  
20                               Fynney, Mr. Joseph J        37.0  
21                              Beesley, Mr. Lawrence        36.0  
22                        McGowan, Miss. Anna "Annie"        18.0  
23                       Sloper, Mr. William Thompson        29.0  
24                      Palsson, Miss. Torborg Danira        11.0  
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...        41.0  
26                            Emir, Mr. Farred Chehab         NaN  
27                     Fortune, Mr. Charles Alexander        20.0  
28                      O'Dwyer, Miss. Ellen "Nellie"         NaN  
29                                Todoroff, Mr. Lalio         NaN  
30                           Uruchurtu, Don. Manuel E        41.0

### Try to fetch a recode starting from 101 until 106 indexes :

In [169]:
data.loc[101:106]

PassengerId  Survived  Pclass                              Name     Sex  \
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  \
101   NaN      0      0   349215   7.8958   NaN        S   
102  21.0      0      1    35281  77.2875   D26        S   
103  33.0      0      0     7540   8.6542   NaN        S   
104  37.0      2      0  3101276   7.9250   NaN        S   
105  28.0      0      0   349207   7.8958   NaN        S   
106  21.0      0      0   343120   7.6500   NaN        S   

                             New_text  Age_Pclass  
101  Petroff, Mr. Pastcho ("Pentcho")         NaN  
102         White, Mr. Richard Frasar        22.0  
103        Johansson, Mr. Gustaf Joel        36.0  
104    Gustafsson, Mr. Anders Vilhelm        40.0  
105             Mionoff, Mr. Stoytcho        31.0  
106  Salkjelsvik, Miss. Anna Kristine        24.0

### Try to fetch a recode starting from 101 until 106 indexes with "Survived" and "New_text" :

In [170]:
data.loc[101:106 , ["New_text"]]

New_text
101  Petroff, Mr. Pastcho ("Pentcho")
102         White, Mr. Richard Frasar
103        Johansson, Mr. Gustaf Joel
104    Gustafsson, Mr. Anders Vilhelm
105             Mionoff, Mr. Stoytcho
106  Salkjelsvik, Miss. Anna Kristine

In [171]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

In [172]:
### add [3,4] insted of [3:4]

data.loc[[3,4] ,["Fare" , "Cabin" ,"Embarked"]]

Fare Cabin Embarked
3  53.10  C123        S
4   8.05   NaN        S

In [173]:
data.loc[102:103 ,["Survived" , "Pclass" ]]

Survived  Pclass
102         0       1
103         0       3

In [174]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

In [175]:
data.iloc[886]

PassengerId                      887
Survived                           0
Pclass                             2
Name           Montvila, Rev. Juozas
Sex                             male
Age                             27.0
SibSp                              0
Parch                              0
Ticket                        211536
Fare                            13.0
Cabin                            NaN
Embarked                           S
New_text       Montvila, Rev. Juozas
Age_Pclass                      29.0
Name: 886, dtype: object

In [176]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

## same Result and compare "loc" and "iloc" :

In [177]:
data.iloc[888:890 , [3,4,5]]

Name     Sex   Age
888  Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                     Behr, Mr. Karl Howell    male  26.0

In [178]:
data.loc[888:889 , ["Name" , "Sex" , "Age"]]

Name     Sex   Age
888  Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                     Behr, Mr. Karl Howell    male  26.0

In [179]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

## fetch All Row  for reach "PassengerId" , "Pclass"

In [180]:
## With  iloc
 
data.loc[ : , ["PassengerId" ,  "Pclass"]]

PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[891 rows x 2 columns]

In [181]:
## With  loc

data.iloc[ : , [0,2]]

PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[891 rows x 2 columns]

In [182]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass  
0                              Braund, Mr. Owen Harris        25.0  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                               Heikkinen, Miss. Laina        29.0  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                             Allen, Mr. William Henry        38.0  
..                                                 ...         ...  
886                              Montvila, Rev. Juozas        29.0  
887                       Graham, Miss. Margaret Edith        20.0  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN  
889                              Behr, Mr. Karl Howell        27.0  
890                                Dooley, Mr. Patrick        35.0  

[891 rows x 14 columns]

## Question :

Give a Row 886 and 888 and colume "PassengerId" , "Survived" , "Pclass" ...........

#Note : we used [886,888] vs [886:888 

In [183]:

data.loc[[886,888] , ["PassengerId" , "Survived" , "Pclass"]]

PassengerId  Survived  Pclass
886          887         0       2
888          889         0       3

In [184]:
data.loc[886:888 , ["PassengerId" , "Survived" , "Pclass"]]

PassengerId  Survived  Pclass
886          887         0       2
887          888         1       1
888          889         0       3

## Question : Age > 35


In [185]:
data[data["Age"] > 35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked  \
1        0  PC 17599  71.2833   C85        C   
6        0     17463  51.8625   E46        S   
11       0    113783  26.5500  C103        S   
13       5    347082  31.2750   NaN        S   
15       0    248706  16.0000   NaN        S   
..     ...       ...      ...   ...      ...   
865      0    236852  13.0000   NaN        S   
871      1     11751  52.5542   D35        S   
873      0    345765   9.0000   NaN        S   
879      1     11767  83.1583   C50        C   
885      5    382652  29.1250   NaN        Q   

                                              New_text  Age_Pclass  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
6                              McCarthy, Mr. Timothy J        55.0  
11                            Bonnell, Miss. Elizabeth        59.0  
13                         Andersson, Mr. Anders Johan        42.0  
15                    Hewlett, Mrs. (Mary D Kingcome)         57.0  
..                                                 ...         ...  
865                           Bystrom, Mrs. (Karolina)        44.0  
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)        48.0  
873                        Vander Cruyssen, Mr. Victor        50.0  
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)        57.0  
885               Rice, Mrs. William (Margaret Norton)        42.0  

[217 rows x 14 columns]

## Question : Age > 35  and Pclass == 1  ???????????

## Create Subset :

In [186]:
data1 = data.iloc[1:6 , [2,3,4,5,9,10]]

In [187]:
data1

Pclass                                               Name     Sex   Age  \
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   

      Fare Cabin  
1  71.2833   C85  
2   7.9250   NaN  
3  53.1000  C123  
4   8.0500   NaN  
5   8.4583   NaN

## Question : pandas.DataFrame.set_index and used inplace = True

### pandas.DataFrame.set_index :

- Pandas set_index() is a method to set a List, Series or Data frame as index of a Data Frame. Index column can be set while making a data frame too. But sometimes a data frame is made out of two or more data frames and hence later index can be changed using this method.

### Parameters: 
- keys: Column name or list of column name.   
- drop: Boolean value which drops the column used for index if True. 
- append: Appends the column to existing index column if True.  
- inplace: Makes the changes in the dataframe if True. 
- verify_integrity: Checks the new index column for duplicates if True. 

https://www.geeksforgeeks.org/python-pandas-dataframe-set_index/

- Signature:
- data.set_index(
    - keys,
      *,
      - drop: 'bool' = True,
      - append: 'bool' = False,
      - inplace: 'bool' = False, ----------> cchange 
      - verify_integrity: 'bool' = False,

In [188]:
data1.set_index("Name",inplace = True)

In [189]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN

## Question : drop all a records where we have "NaN values in a "Rows"

### Pandas DataFrame dropna() Method :
-Remove all rows wit NULL values from the DataFrame.
-Sometimes csv file has null values, which are later displayed as NaN in Data Frame. Pandas dropna() method allows the user to analyze and drop Rows/Columns with Null values in different ways.
 - Syntax : 
   - Signature:
   - axis: 'Axis' = 0, ----> axis takes int or string value for rows/columns. Input can be rows = 0 or columns = 1 for Integer and ‘index’ or ‘columns’ for String.
   - how: 'str | NoDefault' = <no_default>,
   - thresh: 'int | NoDefault' = <no_default>----> thresh: thresh takes integer value which tells minimum amount of na values to drop.
   - subset: 'IndexLabel' = None,
   - inplace: 'bool' = False,

In [190]:
## check Rows :

data1.dropna()

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123

In [191]:
## check Colume : ستونهایی که " ان ای ان " ندارند را جدا می کند 

data1.dropna(axis = 1) 

Pclass     Sex     Fare
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  71.2833
Heikkinen, Miss. Laina                                   3  female   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  53.1000
Allen, Mr. William Henry                                 3    male   8.0500
Moran, Mr. James                                         3    male   8.4583

In [192]:
## Used thresh: 
## thresh = 1 means one "NaN" value is required in colume 
data1.dropna(axis = 1 , thresh = 1)

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN

In [193]:
## thresh = 3 means more than there  "NaN" value is required in colume 
data1.dropna(axis = 1 , thresh = 3)

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare  
Name                                                         
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833  
Heikkinen, Miss. Laina                               7.9250  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  
Allen, Mr. William Henry                             8.0500  
Moran, Mr. James                                     8.4583

In [194]:
data1.dropna(axis = 1 , thresh = 5)

Pclass     Sex     Fare
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  71.2833
Heikkinen, Miss. Laina                                   3  female   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  53.1000
Allen, Mr. William Henry                                 3    male   8.0500
Moran, Mr. James                                         3    male   8.4583

In [195]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN

### Python | Pandas DataFrame.fillna() to replace Null values in dataframe :

 - Just like pandas dropna() method manage and remove Null values from a data frame, fillna() manages and let the user replace NaN values with some value of their own. 
 
 -Signature:
data1.fillna(
- value: 'Hashable | Mapping | Series | DataFrame' = None,
    *,
- method: 'FillnaOptions | None' = None,
- axis: 'Axis | None' = None,
- inplace: 'bool' = False,
- limit: 'int | None' = None,
- downcast: 'dict | None' = None,

In [196]:
### Replace "Farshid" insted of "NaN" 

data1.fillna("Farshid")

Pclass     Sex      Age  \
Name                                                                          
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female     38.0   
Heikkinen, Miss. Laina                                   3  female     26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female     35.0   
Allen, Mr. William Henry                                 3    male     35.0   
Moran, Mr. James                                         3    male  Farshid   

                                                       Fare    Cabin  
Name                                                                  
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833      C85  
Heikkinen, Miss. Laina                               7.9250  Farshid  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000     C123  
Allen, Mr. William Henry                             8.0500  Farshid  
Moran, Mr. James                                     8.4583  Farshid

In [197]:
### Calculate Means of all "Age" and replace to "NaN"

data1.fillna(data1["Age"].mean())

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male  33.5   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250  33.5  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500  33.5  
Moran, Mr. James                                     8.4583  33.5

### Python | Pandas dataframe.groupby() : 
 -Pandas groupby is used for grouping the data according to the categories and apply a function to the categories. It also helps to aggregate data efficiently.
 -Signature:
data1.groupby(
- by=None,
- axis: 'Axis' = 0,
- level: 'IndexLabel | None' = None,
- as_index: 'bool' = True,
- sort: 'bool' = True,
- group_keys: 'bool | lib.NoDefault' = <no_default>,
- squeeze: 'bool | lib.NoDefault' = <no_default>,
- observed: 'bool' = False,
- dropna: 'bool' = True,
 


In [198]:
data1.groupby("Sex").count()

Pclass  Age  Fare  Cabin
Sex                             
female       3    3     3      2
male         2    1     2      0

In [199]:
data1.groupby("Sex").mean()

/tmp/ipykernel_77/3633039205.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data1.groupby("Sex").mean()


Pclass   Age       Fare
Sex                              
female  1.666667  33.0  44.102767
male    3.000000  35.0   8.254150

In [200]:
data1.groupby("Sex").sum()

/tmp/ipykernel_77/1095502595.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data1.groupby("Sex").sum()


Pclass   Age      Fare
Sex                           
female       5  99.0  132.3083
male         6  35.0   16.5083

In [201]:
data1.groupby("Sex").sum()["Fare"]

/tmp/ipykernel_77/3623210938.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data1.groupby("Sex").sum()["Fare"]


Sex
female    132.3083
male       16.5083
Name: Fare, dtype: float64

In [202]:
data1.groupby("Sex").mean()["Age"]

/tmp/ipykernel_77/3637869686.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data1.groupby("Sex").mean()["Age"]


Sex
female    33.0
male      35.0
Name: Age, dtype: float64

In [203]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN

In [204]:
data2 = data.iloc[0:5 , 0:5]

In [205]:
data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  
0                            Braund, Mr. Owen Harris    male  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                             Heikkinen, Miss. Laina  female  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                           Allen, Mr. William Henry    male

### How To Concatenate Two or More Pandas DataFrames? :
-A concatenation of two or more data frames can be done using pandas.concat() method. concat() in pandas works by combining Data Frames across rows or columns. We can concat two or more data frames either along rows  (axis=0) or along columns (axis=1)

## Question : Try to Merge data :
-We have data1 and data2 and we want to merge horizontal and vertical.
- axis: 'Axis' = 0,
- join: 'str' = 'outer',
- ignore_index: 'bool' = False,
- keys=None,
- levels=None,
- names=None,
- verify_integrity: 'bool' = False,
- sort: 'bool' = False,
- copy: 'bool' = True,

- https://pandas.pydata.org/docs/reference/api/pandas.concat.html

In [206]:
##horizontal
pd.concat([data1,data2])

Pclass     Sex   Age  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   
0                                                        3    male   NaN   
1                                                        1  female   NaN   
2                                                        3  female   NaN   
3                                                        1  female   NaN   
4                                                        3    male   NaN   

                                                       Fare Cabin  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85   
Heikkinen, Miss. Laina                               7.9250   NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123   
Allen, Mr. William Henry                             8.0500   NaN   
Moran, Mr. James                                     8.4583   NaN   
0                                                       NaN   NaN   
1                                                       NaN   NaN   
2                                                       NaN   NaN   
3                                                       NaN   NaN   
4                                                       NaN   NaN   

                                                    PassengerId  Survived  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...          NaN       NaN   
Heikkinen, Miss. Laina                                      NaN       NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                NaN       NaN   
Allen, Mr. William Henry                                    NaN       NaN   
Moran, Mr. James                                            NaN       NaN   
0                                                           1.0       0.0   
1                                                           2.0       1.0   
2                                                           3.0       1.0   
3                                                           4.0       1.0   
4                                                           5.0       0.0   

                                                                                                 Name  
Cumings, Mrs. John Bradley (Florence Briggs Tha...                                                NaN  
Heikkinen, Miss. Laina                                                                            NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)                                                      NaN  
Allen, Mr. William Henry                                                                          NaN  
Moran, Mr. James                                                                                  NaN  
0                                                                             Braund, Mr. Owen Harris  
1                                                   Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                                                                              Heikkinen, Miss. Laina  
3                                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                                                                            Allen, Mr. William Henry

## try to change axis :

In [207]:
## Vertical
pd.concat([data1,data2] , axis = 1)

Pclass     Sex   Age  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...     1.0  female  38.0   
Heikkinen, Miss. Laina                                 3.0  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1.0  female  35.0   
Allen, Mr. William Henry                               3.0    male  35.0   
Moran, Mr. James                                       3.0    male   NaN   
0                                                      NaN     NaN   NaN   
1                                                      NaN     NaN   NaN   
2                                                      NaN     NaN   NaN   
3                                                      NaN     NaN   NaN   
4                                                      NaN     NaN   NaN   

                                                       Fare Cabin  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85   
Heikkinen, Miss. Laina                               7.9250   NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123   
Allen, Mr. William Henry                             8.0500   NaN   
Moran, Mr. James                                     8.4583   NaN   
0                                                       NaN   NaN   
1                                                       NaN   NaN   
2                                                       NaN   NaN   
3                                                       NaN   NaN   
4                                                       NaN   NaN   

                                                    PassengerId  Survived  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...          NaN       NaN   
Heikkinen, Miss. Laina                                      NaN       NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                NaN       NaN   
Allen, Mr. William Henry                                    NaN       NaN   
Moran, Mr. James                                            NaN       NaN   
0                                                           1.0       0.0   
1                                                           2.0       1.0   
2                                                           3.0       1.0   
3                                                           4.0       1.0   
4                                                           5.0       0.0   

                                                    Pclass  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...     NaN   
Heikkinen, Miss. Laina                                 NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)           NaN   
Allen, Mr. William Henry                               NaN   
Moran, Mr. James                                       NaN   
0                                                      3.0   
1                                                      1.0   
2                                                      3.0   
3                                                      1.0   
4                                                      3.0   

                                                                                                 Name  \
Cumings, Mrs. John Bradley (Florence Briggs Tha...                                                NaN   
Heikkinen, Miss. Laina                                                                            NaN   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                                                      NaN   
Allen, Mr. William Henry                                                                          NaN   
Moran, Mr. James                                                                                  NaN   
0                                                                             Braund, Mr. Owen Harris   
1                                                   Cumings, Mrs. John Bradley (Florence Briggs Th...   
2                                                                              Heikk

In [208]:
data1


Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  
Name                                                               
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  
Heikkinen, Miss. Laina                               7.9250   NaN  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  
Allen, Mr. William Henry                             8.0500   NaN  
Moran, Mr. James                                     8.4583   NaN

## Add own Function to Pandas (External function add to particular column)

### Applying Lambda functions to Pandas Dataframe :
-In Pandas, we have the freedom to add different functions whenever needed like lambda function, sort function, etc. We can apply a lambda function to both the columns and rows of the Pandas data frame.
-pandas.DataFrame.apply() can be used with python lambda to execute expression. A lambda function in python is a small anonymous function that can take any number of arguments and execute an expression.
- Syntax : 
- DataFrame.apply(func, 
- axis=0, 
- *raw=False, 
- result_type=None, 
- args=(), 
- **kwargs)
- https://www.geeksforgeeks.org/applying-lambda-functions-to-pandas-dataframe/

### .apply(lambda x :  )

In [218]:
data1["new"] = data1["Pclass"]

In [221]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin  new  
Name                                                                    
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85    1  
Heikkinen, Miss. Laina                               7.9250   NaN    3  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123    1  
Allen, Mr. William Henry                             8.0500   NaN    3  
Moran, Mr. James                                     8.4583   NaN    3

In [224]:
### We want to divided Pclass by 3 ??????????? (We used lambda)

data1["new"] = data1["Pclass"].apply(lambda x : x/3) 

In [225]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin       new  
Name                                                                         
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  0.333333  
Heikkinen, Miss. Laina                               7.9250   NaN  1.000000  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  0.333333  
Allen, Mr. William Henry                             8.0500   NaN  1.000000  
Moran, Mr. James                                     8.4583   NaN  1.000000

## Add own Function to Pandas (External function add to particular column)

In [230]:
def fun1(x):
    return x/3

In [227]:
data1["new"] = data1["Pclass"].apply(fun1) 

In [228]:
data1

Pclass     Sex   Age  \
Name                                                                       
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
Moran, Mr. James                                         3    male   NaN   

                                                       Fare Cabin       new  
Name                                                                         
Cumings, Mrs. John Bradley (Florence Briggs Tha...  71.2833   C85  0.333333  
Heikkinen, Miss. Laina                               7.9250   NaN  1.000000  
Futrelle, Mrs. Jacques Heath (Lily May Peel)        53.1000  C123  0.333333  
Allen, Mr. William Henry                             8.0500   NaN  1.000000  
Moran, Mr. James                                     8.4583   NaN  1.000000

## Create data to store length of "Name"    

In [231]:
data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  
0                            Braund, Mr. Owen Harris    male  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                             Heikkinen, Miss. Laina  female  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                           Allen, Mr. William Henry    male

In [233]:
data2["length_name"] = data2["Name"].apply(len)

In [234]:
data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  length_name  
0                            Braund, Mr. Owen Harris    male           23  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female           51  
2                             Heikkinen, Miss. Laina  female           22  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           44  
4                           Allen, Mr. William Henry    male           24

##  Create a new column when "PassengerId" lesser than 3 keep a data as it is(No change) , and when greater or equel to 3 try to 
## find of "logarithm" of data .

In [236]:
import math
def cust1(x):
    if x < 3:
        return x
    else :
        return math.log10(x)

In [237]:
data2["PassengerId_Filter"] = data2["PassengerId"].apply(cust1)

In [238]:
data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  length_name  \
0                            Braund, Mr. Owen Harris    male           23   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female           51   
2                             Heikkinen, Miss. Laina  female           22   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           44   
4                           Allen, Mr. William Henry    male           24   

   PassengerId_Filter  
0            1.000000  
1            2.000000  
2            0.477121  
3            0.602060  
4            0.698970

## Wherever we have a female try to make it as 1 and for male add 0

In [240]:
def test2(x):
    if x == "female" : 
        return 1
    else:
        return 0

In [241]:
data2["Sex_test2"] = data2["Sex"].apply(test2)

In [242]:
data2

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  length_name  \
0                            Braund, Mr. Owen Harris    male           23   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female           51   
2                             Heikkinen, Miss. Laina  female           22   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female           44   
4                           Allen, Mr. William Henry    male           24   

   PassengerId_Filter  Sex_test2  
0            1.000000          0  
1            2.000000          1  
2            0.477121          1  
3            0.602060          1  
4            0.698970          0

In [243]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  \
0      0         A/5 21171   7.2500   NaN        S   
1      0          PC 17599  71.2833   C85        C   
2      0  STON/O2. 3101282   7.9250   NaN        S   
3      0            113803  53.1000  C123        S   
4      0            373450   8.0500   NaN        S   
5      0            330877   8.4583   NaN        Q   
6      0             17463  51.8625   E46        S   
7      1            349909  21.0750   NaN        S   
8      2            347742  11.1333   NaN        S   
9      0            237736  30.0708   NaN        C   

                                            New_text  Age_Pclass  
0                            Braund, Mr. Owen Harris        25.0  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0  
2                             Heikkinen, Miss. Laina        29.0  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0  
4                           Allen, Mr. William Henry        38.0  
5                                   Moran, Mr. James         NaN  
6                            McCarthy, Mr. Timothy J        55.0  
7                     Palsson, Master. Gosta Leonard         5.0  
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)        30.0  
9                Nasser, Mrs. Nicholas (Adele Achem)        16.0

## Average of "Age" in "NaN" value (Pandas DataFrame.fillna() "NaN" values") - 
### Based on "Fare" separate customers "A" , "B" ,"C" and filtred .

- 0-100   - "A"
- 101-199 - "B"
- 200+    - "C" 

In [245]:
def test3(x):
    if x <= 100 : 
        return "A"
    elif x > 100 and x < 200:
        return "B"
    else :
        return "C"

In [247]:
data["Fare_Group"] = data["Fare"].apply(test3) 

In [248]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  \
0        0         A/5 21171   7.2500   NaN        S   
1        0          PC 17599  71.2833   C85        C   
2        0  STON/O2. 3101282   7.9250   NaN        S   
3        0            113803  53.1000  C123        S   
4        0            373450   8.0500   NaN        S   
..     ...               ...      ...   ...      ...   
886      0            211536  13.0000   NaN        S   
887      0            112053  30.0000   B42        S   
888      2        W./C. 6607  23.4500   NaN        S   
889      0            111369  30.0000  C148        C   
890      0            370376   7.7500   NaN        Q   

                                              New_text  Age_Pclass Fare_Group  
0                              Braund, Mr. Owen Harris        25.0          A  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        39.0          A  
2                               Heikkinen, Miss. Laina        29.0          A  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        36.0          A  
4                             Allen, Mr. William Henry        38.0          A  
..                                                 ...         ...        ...  
886                              Montvila, Rev. Juozas        29.0          A  
887                       Graham, Miss. Margaret Edith        20.0          A  
888           Johnston, Miss. Catherine Helen "Carrie"         NaN          A  
889                              Behr, Mr. Karl Howell        27.0          A  
890                                Dooley, Mr. Patrick        35.0          A  

[891 rows x 15 columns]